kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/cpf13/jenkins-docker-demo

steps:
  - name: test
    image: golang
    commands:
      - go get
      - go test
  - name: build
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output
  - name: run
    image: golang
    commands:
      - go get
      - go build - output
      - chmod +x output
      - ./ouput